name: Deploy Godot Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Build & Deploy
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5

      - name: Export Godot Project
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://downloads.godotengine.org/?version=4.6&flavor=stable&slug=linux.x86_64.zip&platform=linux.64
          godot_export_templates_download_url: https://downloads.godotengine.org/?version=4.6&flavor=stable&slug=export_templates.tpz&platform=templates
          relative_project_path: ./
          cache: true
          archive_output: false
          use_preset_export_path: true

      - name: Prepare Web Assets
        run: |
          mv ./exports/web/Web/* ./exports/web/
          rm -rf ./exports/web/Web

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./exports/web
